# Nueral Network From Scratch


## Simple Nueron

In [2]:
inputs = [1 , 2 , 3]
weight = [.2 , .8 , -.5]
bias = 2

In [3]:
output = inputs[0]*weight[0] + inputs[1]*weight[1]+inputs[2]*weight[2] + bias 

In [4]:
print(output)

2.3


## layer of nueron


In [5]:
inputs = [1, 2, 3, 2.5] 
 
weights1 = [0.2, 0.8, -0.5, 1] 
weights2 = [0.5, -0.91, 0.26, -0.5] 
weights3 = [-0.26, -0.27, 0.17, 0.87] 
 
b1 = 2 
b2 = 3 
b3 = 0.5 

In [6]:
outputs = [ 
        # Neuron 1: 
        inputs[0]*weights1[0] + 
        inputs[1]*weights1[1] + 
        inputs[2]*weights1[2] + 
        inputs[3]*weights1[3] + b1, 
 
        # Neuron 2: 
        inputs[0]*weights2[0] + 
        inputs[1]*weights2[1] + 
        inputs[2]*weights2[2] + 
        inputs[3]*weights2[3] + b2, 
 
        # Neuron 3: 
        inputs[0]*weights3[0] + 
        inputs[1]*weights3[1] + 
        inputs[2]*weights3[2] + 
        inputs[3]*weights3[3] + b3] 

In [7]:
print(outputs)

[4.8, 1.21, 2.385]


## Single Neuron with numpy

In [8]:
import numpy as np
inputs = [1 , 2 , 3]
weight = [.2 , .8 , -.5]
bias = 2

In [9]:
output = np.dot(inputs,weight) + bias

In [10]:
print (output)

2.3


## layer of neuron with numpy

In [11]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1] ,
           [0.5, -0.91, 0.26, -0.5] ,
           [-0.26, -0.27, 0.17, 0.87]]
b = [2 , 3 , .5]

In [12]:
output=np.dot(weights,inputs)+b

In [13]:
print(output)

[4.8   1.21  2.385]


In [14]:
a = [1, 2, 3] 
np.array([a]) 

array([[1, 2, 3]])

In [15]:
print(np.expand_dims(np.array(a),axis=0))

[[1 2 3]]


## 2 Layers of Nueron

In [16]:
inputs = [[1, 2, 3, 2.5], [2., 5., -1., 2], [-1.5, 2.7, 3.3, -0.8]] 
weights = [[0.2, 0.8, -0.5, 1], 
           [0.5, -0.91, 0.26, -0.5], 
           [-0.26, -0.27, 0.17, 0.87]] 
biases = [2, 3, 0.5] 
weights2 = [[0.1, -0.14, 0.5], 
            [-0.5, 0.12, -0.33], 
            [-0.44, 0.73, -0.13]] 
biases2 = [-1, 2, -0.5]


In [17]:
layer1_output = np.dot(inputs,np.array(weights).T)+biases

In [18]:
layer2_output = np.dot(layer1_output,np.array(weights2).T)+biases2

In [19]:
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


## Dence layer with forward path

In [56]:
class layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weight=0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases= np.zeros((1,n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs,self.weight)+self.biases

In [57]:
import nnfs 
from nnfs.datasets import spiral_data
x,y = spiral_data(samples = 100 , classes = 3)

In [58]:
dense1= layer_dense(2,3)
dense1.forward(x)

In [59]:
print(dense1.output[:5]) 

[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.59338263e-05 1.72752182e-05 5.34774791e-05]
 [1.39686329e-04 3.08581083e-05 9.30183788e-05]
 [1.47555748e-04 5.38950809e-05 1.68536737e-04]
 [3.58486035e-04 4.52516832e-05 1.26723588e-04]]


## Relu activation function

In [1]:
class activation_relu :
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)